### ISSUE TITLE
Очная сдача

### ISSUE THREAD

**Issue by coursar** [sunatullo-gafurov/map-filter-reduce#1]
Эту задачу надо было сдавать очно. Если хотите сдавать так, то мне нужны ответы на три вопроса:
1. Какие две разновидности `reduce` применяются? Когда и почему?
2. Как отладить функции-однострочники (присылайте скриншоты) - как попасть внутрь
3. Как работает 9.4 нужно объяснить по шагам в картинках

Если сможете - ок, нет - тогда и разговора нет.

**Comment by sunatullo-gafurov** [comment]
1. Reduce принимает два аргумента: callback function и initial value. 
У коллбэк функции есть две обязательные аргументы: аккумулятор и текущее значение.
Для каждого элемента внутри массив, на котором мы будем использовать reduce( ) method, reduce( ) будет выполнять функцию коллбэк. Если массив состоит из объектов то начальное значение будет обязательном. Например:
const arr = [1, 2, 3, 4];
const reduced = arr.reduce((acc, curr) => acc + curr, 6);
Здесь начальное значение равно 6.
Тогда acc будет 6.
На первом итерации акк=6 и курр=1, функция коллбэк возвращает 6+1=7 и акк берет на себя значению 7.
На втором итерации акк=7 и курр=2, функция коллбэк возвращает 7+2=9 и акк берет на себя значению 9.
На третий раз акк=9 и курр=3, функция коллбэк возвращает 9+3=12 и в конце нам возвращает число 12.
console.log(reduced) // 12.
Если мы не дадим начальную значению тогда акк берет на себя первую элемент массива как значение а курр будет второй элемент массива.

**Comment by sunatullo-gafurov** [comment]
![3](https://user-images.githubusercontent.com/55190130/73946697-25c60a80-4918-11ea-88d4-b940fc0cd5f0.JPG)
![1](https://user-images.githubusercontent.com/55190130/73946728-35455380-4918-11ea-997a-ce120e3b4114.JPG)
![2](https://user-images.githubusercontent.com/55190130/73946733-38404400-4918-11ea-9b99-fbee850d9704.JPG)

**Comment by sunatullo-gafurov** [comment]
![1](https://user-images.githubusercontent.com/55190130/73948000-2d86ae80-491a-11ea-9433-b093f9751ba6.JPG)

1) map нам возвращает новуя массив.
Для каждого элемента(i) внутри purchases(arr) делаем map на i.values.
Для каждого элемента(j) внутри i.values, нам возвращает объект {category: j.category, amount: j.amount}. В конце у нас получается: 
const mapped = [
[
{category: "auto", amount: 2000}, 
{category: "food", amount: 3000},
{category: "beauty", amount: 300}
],
[
{category: "auto", amount: 3000},
{category: "travel", amount: 30000}
],
[
{category: "food", amount: 3000}
]
];
Используем flat( ) чтобы объединить массивы
mapped.flat( ) нам возвращает 
[
{category: "auto", amount: 2000},
{category: "food", amount: 3000},
{category: "beauty", amount: 300},
{category: "auto", amount: 3000},
{category: "travel", amount: 30000},
{category: "food", amount: 3000}
] 
![2](https://user-images.githubusercontent.com/55190130/73950272-75f39b80-491d-11ea-8311-69088610c721.JPG)

2) Теперь создаем пустую объект.
Сделаем итерациу на mapped с for const item of mapped
Если у нашего объекта есть свойство item.category тогда на ту свойству прибавим item.amount
Если у объекта нет свойство item.category тогда обозначаем item.category на объект(obj).
![3](https://user-images.githubusercontent.com/55190130/73952006-44c89a80-4920-11ea-8bc4-fd9e61c34d85.JPG)

3) Создаем переменны max and returnCategory и дадим значение 0 на max.
Заходим внутри obj с помощью for const key in obj цикл
Если max меньше чем obj[key] тогда меняем max на obj[key], а returnCategory на key.
В конце max будет самая дорогая покупка, а returnCategory будет ее категория, и нам надо возвращать категорию,
return returnCategory;
